### PR TITLE
More EFIS improvements (mostly PFD)

### PR DESCRIPTION
**Pull request by tdammers**

### CODE REVIEW

**Comment by YV3399** [comment]
Thank you very much, we have to review some things:
the fdm is broken
livery system is broken
adjustment does not work because fin changes destabilize overall fdm
all that was fine but surely the problem started from the improvements to the flaps, in fact the animation of the flaps is also broken :/

**Comment by tdammers** [comment]
> the fdm is broken

Yes, it is, but nothing I touched can possibly have caused that. The only thing I did to the FDM was reduce the amount of drag induced by flaps. Any breakage of the FDM that exists now has already been there before I started.

A few symptoms that caught my eye:

- Flaps induce too much drag (attempted to less that, with some success).
- Flaps seem to affect the center of lift a lot, which causes pitch oscillation on flap extension and makes it difficult to control the aircraft on approach as you extend flaps. Not sure where exactly the problem originates though, could be the flaps just extend too fast, or the flap positions may be wrong, or they just produce too much drag (and maybe also too much lift).
- Takeoff climb performance is way too powerful (typical takeoff climb speed is 165 KIAS at T/O thrust, and achieves about 1600-1800 fpm; in our model, the same 165 KIAS speed climb causes the A/P pulls up to 25 degrees nose-up, and the aircraft climbs at more than 4000 fpm).
- In cruise, the aircraft maintains a ~5 degree nose-up attitude. This seems wrong. Achievable cruise speeds are realistic though, so I believe the problem isn't too much drag, but rather improper mass balancing.

> livery system is broken

Liveries look fine on my end, not sure what's broken. I haven't done any extensive testing on this one though, because nothing I did touches the external models or liveries in any way.

> adjustment does not work because fin changes destabilize overall fdm

Not 100% sure what you mean by "fin changes".

If you mean elevator deflection, then this is due to lack of autopilot tuning (haven't gotten around to re-tuning ITAF after the upgrade, but it wasn't very good before the upgrade either).

If you mean flap extension: that one is as broken now as it was before. I think the problem is that flaps extend too abruptly, and the flap-induced drag and lift may both be too much still.

> all that was fine but surely the problem started from the improvements to the flaps, in fact the animation of the flaps is also broken :/

Again, the only thing I did was reduce flap drag. If anything, that ought to reduce the effects you describe, and it absolutely cannot have any impact whatsoever on animations.

On that note, there are other animations that are broken:

- Reversers only animate on one side (starboard, off the top of my head)
- One of the multipurpose spoilers on the left wing is animated all wrong I think it rotates together with the flaps, but the pivot axis is all wrong

Anyway, none of that was touched in this PR, and it's unlikely that I caused any of it in any of my other commits, so maybe the best thing to do would be to move these discussions into separate issues.

**Comment by YV3399** [comment]
Thanks for your answer and explanation, today I will review everything and I will try to fix the most serious problems quickly.

-I saw all those problems that you described on a test flight, it is a confusing airplane but surely the one that causes so many errors must be somewhat minimal, since long before it was flying well, flaps were always a problem and it is because they cause a lot of resistance and they move very fast, which causes a strong movement, we have to find a good solution. Anyway thanks, you are doing a great job, regards.

**Comment by legoboyvdlp** [comment]
I have corrected the speed of the flaps to be better, pull request coming :)

**Comment by YV3399** [comment]
Thanks lego, what do you think of the error with the fdm? I think I didn't have that problem with the elevator before

**Comment by legoboyvdlp** [comment]
I'm not really sure, sorry. Can you describe what happens? Is it the autopilot needing tuned or the fdm elevator response?

**Comment by tdammers** [comment]
The autopilot definitely needs tuning.

Elevator response in manual flight feels OK to me; but when the A/P is flying, it sometimes oscillates, e.g. when capturing the glideslope, and it seems to have trouble dealing with thrust changes and flap setting changes on final.

ITAF 4.0 uses different configuration parameters though, and I basically guessed most of them, so the autopilot definitely needs re-tuning.

**Pull request merged**
